services:
  - type: web
    name: greencare-backend
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: DATABASE_URL
        value: sqlite:///./greencare.db
